# Apply system updates
- name: Update packages to latest versions
  apt:
    name: "*"
    state: latest
    update_cache: yes

# Install additional packaages
- name: Install latest version of 'openjdk-17-jdk-headless'
  apt:
    name: "openjdk-17-jdk-headless"
    state: latest

- name: Install latest version of 'screen'
  apt:
    name: "screen"
    state: latest

- name: Install latest version of 'fail2ban'
  apt:
    name: "fail2ban"
    state: latest

# Creation and configuration of non root user
- name: Add the user 'server-admin' with a bash shell, added to 'admin' group
  user:
    name: server-admin
    password: "{{ user_password | password_hash('sha512') }}"
    shell: /bin/bash
    groups: admin
    append: yes

- name: Create .ssh directory if it does not exist
  file:
    path: /home/server-admin/.ssh/
    state: directory
    owner: server-admin
    group: server-admin
    mode: '0700'

- name: Copy ssh public key to new user .ssh directory
  copy:
    src: ~/.ssh/server_rsa.pub
    dest: /home/server-admin/.ssh
    owner: server-admin
    group: server-admin

- name: Rename copied pulic key authorized_keys directory if it does not exist
  copy:
    remote_src: yes
    src: /home/server-admin/.ssh/server_rsa.pub
    dest: /home/server-admin/.ssh/authorized_keys
    owner: server-admin
    group: server-admin
    mode: '0600'

# Configure server firewall
- name: Enable OpenSSH profile
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Allow port 25565
  community.general.ufw:
    rule: allow
    port: '25565'

- name: Enable UFW
  community.general.ufw:
    state: enabled

# Configure Fail2Ban
- name: Copy Fail2Ban conf to local
  copy:
    remote_src: yes
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.local

- name: Restart Fail2Ban service
  service:
    name: fail2ban
    state: restarted

# Reboot machine and disable root login to finalize setup
- name: Reboot the machine
  reboot:
    reboot_timeout: 120

- name: Disable Root Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present

- name: Restart sshd service
  service:
    name: sshd
    state: restarted